/*BEST PERFORMING WAITERS*/

SELECT T.WAITERID, W.NAME, SUM(T.TIP) AS TOTAL_TIP
FROM (SELECT T.ORDERID, T.SERVICERATING, O.WAITERID, O.TIP
		FROM (SELECT ORDERID, SERVICERATING
				FROM RESTAURANT.FEEDBACK
				WHERE SERVICERATING > 7) AS T,
				RESTAURANT.ORDERS AS O
				WHERE O.ORDERID = T.ORDERID) AS T,
RESTAURANT.WAITER AS W
WHERE W.WAITERID = T.WAITERID
GROUP BY T.WAITERID
ORDER BY TOTAL_TIP DESC