/*TOP 10 VISITING CUSTOMERS*/

SELECT O.CUSTOMERID, C.NAME, COUNT(O.CUSTOMERID) AS NUMBER_OF_VISITS
FROM RESTAURANT.ORDERS AS O, RESTAURANT.CUSTOMER AS C
WHERE C.CUSTOMERID = O.CUSTOMERID
GROUP BY O.CUSTOMERID
ORDER BY COUNT(O.CUSTOMERID) DESC
LIMIT 10;