SELECT S.SUPPLIERID, S.SUPPLIERNAME, T.ID, SUM(T.COUNT_OF_DISH) AS GROCERIES_BOUGHT_PER_STORE
FROM (SELECT M.ID, D.COUNT_OF_DISH
		FROM RESTAURANT.MAKES_USE AS M
		INNER JOIN (SELECT DISHID, COUNT(DISHID) AS COUNT_OF_DISH
					FROM RESTAURANT.CONSIST_OF
					GROUP BY DISHID
					ORDER BY COUNT(DISHID) DESC
					LIMIT 3) AS D
				ON D.DISHID = M.DISHID
		GROUP BY M.ID) AS T,
RESTAURANT.INGREDIENTS AS I,
RESTAURANT.SUPPLIER AS S
WHERE I.ID = T.ID AND S.SUPPLIERID = I.SUPPLIERID
GROUP BY S.SUPPLIERID
ORDER BY GROCERIES_BOUGHT_PER_STORE DESC;